apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gh-runner
  template:
    metadata:
      labels:
        app: gh-runner
    spec:
      containers:
      - image: myoung34/github-runner:latest
        name: guestbook-ui
